---
title: "Using The GUI"
output:   
  html_document:
    theme: yeti
---

## 
	1.	Navigate to the “Directory Selection” tab to choose the directory containing your FCS/CSV files and the destination directory for your results. When completed, click the ‘Load Directories’ button. Once you see the confirmation message, proceed to step 2. 
	2.	Navigate to the “Settings” tab and enter all of the relevant information for you FLOWMAP analysis. When completed, click the ‘Submit’ button. Once you see the confirmation message, proceed to step 3. 
	3.	Navigate to the “File Processing” tab and select whether the data should be analyzed by FLOWMAPR mode "one", "single", or "multi". Once selected, this tab will populate with the relevant fields for that mode. The usage from this point on differs depending on what mode (e.g. "multi" or "single" or "one") is used.

## Mode-Specific Instructions {.tabset .tabset-pills}

### One
#### For mode "one" (one condition, one timepoint):
	1.	Select the FCS file to be analyzed in "Uploaded Order".
	2.	Press "Generate Parameters".
	3.	An interactive table will appear with all the parameters as well as options for selecting and deselecting them as clustering or removed variables. Removed variables will not be in the final generated graph, such as in the graphml file or the image PDFs.
	4.	You must check at least one or more of the parameters for clustering. These variables are used both for clustering (calculation of similarity) and for calculating edge distances during the graph building steps. If you want to rename a parameter, you can click on the name under the "annotate" column and type a new name.
	5.	Press "Run FLOWMAPR" once the appropriate parameters have been checked and renamed to run the FLOW-MAP algorithm and generate all requested FLOWMAPR results (PDFs, graphml files, etc. in a new folder).

### Single
#### For mode "single" (one condition, one timepoint):
	1.	Enter in the order of the FCS files that you wish to use. Generally, files will be used in an alphanumerical order by time, but here you can specify the ordering if the naming system does not reflect the order you want.
	2.	Press "Generate Parameters".
	3.	Two things will happen: an interactive table will appear with all the parameters and options for selecting how parameters should be used for analysis, and the menus for "Similar Fields" and "Different Fields" will autopopulate as an aid to help you process channels between the files.
	4.	If any channel needs to be merged, select the files from the "Different Fields" window, enter the new merged name in "Select New Merge Name", and press "Merge Selected Diff". This will automatically remove the channels from "Different Fields", add the merged name to "Similar Fields", and will update the table with new annotations.
	5.	The different parameters will by default be checked for removal. You must check at least one or more of the parameters for clustering. If you want to rename a parameter, click on the name under "annotate" and type a new name.
	6.	Press "Run FLOWMAPR" once the appropriate parameters have been checked and renamed to run the FLOW-MAP algorithm and generate all requested FLOWMAPR results (PDFs, graphml files, etc. in a new folder).

### Multi
#### For mode "multi" (one condition, one timepoint):
	1.	Select the CSV file that has the corresponding FCS file paths. How the CSV file should be arranged (i.e. what information is put in the columns/rows) will be shown in the following section.
	2.	Press "Input CSV" once the CSV is selected in the box.
	3.	If any channel needs to be merged, select the files from the "Different Fields" window, enter the new merged name in "Select New Merge Name", and press "Merge Selected Diff". This will automatically remove the channels from "Different Fields", add the merged name to "Similar Fields", and will update the table with new annotations.
	4.	The different parameters will by default be checked for removal. You must check at least one or more of the parameters for clustering. If you want to rename a parameter, click on the name under "annotate" and type a new name.
	5.	Press "Run FLOWMAPR" once the appropriate parameters have been checked and renamed to run the FLOW-MAP algorithm and generate all requested FLOWMAPR results (PDFs, graphml files, etc. in a new folder).
