#' FLOWMAPR - Graph-based visualizations of high-dimensional single-cell data across time
#'
#' @description
#' An Implementation of FLOW-MAP Algorithm in R. It takes user-specified
#' inputs for settings of a FLOW-MAP analysis and generates a FLOW-MAP graph from provided
#' FCS files or dataframes. Results include graphml files for the FLOW-MAP graph as well
#' as a graph resolved by a force-directed layout, as well as auto-generated PDFs for
#' the resolved graph colored by each node parameter. A summary text file is autogenerated to
#' summarize the settings of a particular run. A Shiny GUI is also available to establish
#' FLOW-MAP settings and begin a FLOW-MAP analysis. Please see the accompanying README.md
#' file and our GitHub repo at \url{https://github.com/zunderlab/FLOWMAP/} for
#' more detailed instructions and examples.
#'
#' @name FLOWMAPR
#' @docType package
#' @import flowCore
#' @import robustbase
#' @import igraph
#' @import scaffold
#' @import SDMTools
#' @import rhandsontable
#' @import shiny
#' @import shinythemes
#' @import shinyFiles
#' @import shinydashboard
#' @import shinyalert
#' @import flowCore
NULL
